"""
Gold Loan System - PREMIUM Edition
Auto-generated by ZORO9X SaaS Platform
"""

import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import sqlite3
import json
import os
import hashlib
import platform
import uuid
import requests
import webbrowser
from datetime import datetime
import base64
import sys
import hmac

# Configuration
APP_DIR = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(APP_DIR, 'gold_loan_config.json')
LICENSE_CACHE_FILE = os.path.join(APP_DIR, 'gold_loan_license.json')
DEFAULT_OFFLINE_GRACE_MINUTES = 3
DEFAULT_OFFLINE_GRACE_DAYS = 7
API_URL = 'https://www.zoro9x.com'
PAYMENT_PORTAL_URL = f'{API_URL}/client-dashboard'
VALIDATE_ENDPOINT = '/api/saas/validate-key'
ACTIVATE_ENDPOINT = '/api/saas/activate-device'
HEARTBEAT_ENDPOINT = '/api/saas/heartbeat'
TOKEN_VERIFY_SECRET = 'your_jwt_secret_key_change_this_in_production_12345678'
CONFIG_SIGNING_SECRET = 'your_jwt_secret_key_change_this_in_production_12345678'


def get_effective_api_url():
    return API_URL.rstrip('/')


def is_remote_api_url(url):
    normalized = (url or '').strip().lower()
    return bool(normalized and (normalized.startswith('http://') or normalized.startswith('https://')))


def xor_bytes(data, key_material):
    key = hashlib.sha256(key_material.encode()).digest()
    return bytes(byte ^ key[index % len(key)] for index, byte in enumerate(data))


def encrypt_config_value(value, device_fp):
    if not value:
        return ''
    encrypted = xor_bytes(value.encode('utf-8'), f'config:{device_fp}')
    return base64.b64encode(encrypted).decode('utf-8')


def decrypt_config_value(value, device_fp):
    if not value:
        return ''
    try:
        decoded = base64.b64decode(value.encode('utf-8'))
        decrypted = xor_bytes(decoded, f'config:{device_fp}')
        return decrypted.decode('utf-8')
    except Exception:
        return value


def get_config_value(config, encrypted_key, device_fp, default=''):
    encrypted_value = config.get(encrypted_key, '')
    if encrypted_value:
        return decrypt_config_value(encrypted_value, device_fp)
    return default


def sign_config(config_data, device_fp):
    """Sign encrypted config fields to detect local tampering."""
    signable = {
        'api_key_encrypted': config_data.get('api_key_encrypted', ''),
        'company_name_encrypted': config_data.get('company_name_encrypted', ''),
        'contact_email_encrypted': config_data.get('contact_email_encrypted', ''),
        'contact_phone_encrypted': config_data.get('contact_phone_encrypted', ''),
        'business_address_encrypted': config_data.get('business_address_encrypted', ''),
        'logo_url_encrypted': config_data.get('logo_url_encrypted', ''),
        'database_name': config_data.get('database_name', ''),
        'database_path': config_data.get('database_path', ''),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        CONFIG_SIGNING_SECRET.encode('utf-8'),
        f'config:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_config_signature(config_data, device_fp):
    expected = sign_config(config_data, device_fp)
    provided = config_data.get('config_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def get_device_fingerprint():
    """Generate a stable device fingerprint from hardware identifiers."""
    raw = '|'.join([platform.node(), platform.machine(), str(uuid.getnode())])
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


def get_mac_address():
    """Return local MAC address in colon format for device tracking."""
    mac_num = uuid.getnode()
    mac_hex = f'{mac_num:012x}'
    return ':'.join(mac_hex[i:i+2] for i in range(0, 12, 2))


def parse_token_payload(token):
    """Decode token payload from server token format."""
    try:
        if not token or '.' not in token:
            return {}
        payload_part = token.split('.', 1)[0]
        payload_part += '=' * (-len(payload_part) % 4)
        raw = base64.b64decode(payload_part.encode())
        return json.loads(raw.decode())
    except Exception:
        return {}


def verify_server_signed_token(token):
    """Verify server signature for offline token usage."""
    try:
        if not token or '.' not in token:
            return False, {}

        payload_part, signature = token.split('.', 1)
        if not payload_part or not signature:
            return False, {}

        expected = hmac.new(
            TOKEN_VERIFY_SECRET.encode('utf-8'),
            payload_part.encode('utf-8'),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected):
            return False, {}

        payload = parse_token_payload(token)
        return bool(payload), payload
    except Exception:
        return False, {}


def resolve_grace_period_minutes(payload):
    try:
        if payload.get('grace_period_minutes') is not None:
            return max(1, int(payload.get('grace_period_minutes')))
    except Exception:
        pass

    try:
        grace_days = int(payload.get('grace_period_days') or DEFAULT_OFFLINE_GRACE_DAYS)
    except Exception:
        grace_days = DEFAULT_OFFLINE_GRACE_DAYS

    return max(1, grace_days * 24 * 60)


def sign_cache(cache_data, device_fp):
    """Sign local cache to detect manual edits."""
    signable = {
        'valid': cache_data.get('valid', False),
        'last_check': cache_data.get('last_check', ''),
        'token': cache_data.get('token', ''),
        'subscription_id': cache_data.get('subscription_id'),
        'device_fingerprint': cache_data.get('device_fingerprint', ''),
        'grace_period_minutes': cache_data.get('grace_period_minutes', DEFAULT_OFFLINE_GRACE_MINUTES),
        'grace_period_days': cache_data.get('grace_period_days', DEFAULT_OFFLINE_GRACE_DAYS),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        TOKEN_VERIFY_SECRET.encode('utf-8'),
        f'cache:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_cache_signature(cache_data, device_fp):
    expected = sign_cache(cache_data, device_fp)
    provided = cache_data.get('cache_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def load_license_cache():
    if os.path.exists(LICENSE_CACHE_FILE):
        try:
            with open(LICENSE_CACHE_FILE, 'r') as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_license_cache(data):
    try:
        with open(LICENSE_CACHE_FILE, 'w') as f:
            json.dump(data, f, indent=2)
    except Exception:
        pass


class GoldLoanSystemApp:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("Gold Loan System - Premium Edition")
        self.root.geometry("1400x800")
        self.root.configure(bg='#f5f7fa')
        self.heartbeat_job = None
        
        # Load configuration
        self.config = self.load_config()
        
        # Database configuration
        db_name = self.config.get('database_name', 'gold_loan_premium_database')
        db_path = self.config.get('database_path', f'{db_name}.db')
        self.db_file = db_path if os.path.isabs(db_path) else os.path.join(APP_DIR, db_path)

        self.company_name = self.config.get('company_name', 'My Business')
        self.business_phone = self.config.get('contact_phone', '')
        self.business_email = self.config.get('contact_email', '')
        self.business_address = self.config.get('business_address', '')
        self.logo_url = self.config.get('logo_url', '')

        # Validate license before allowing access
        if not self.validate_license():
            self.root.destroy()
            return
        
        # Initialize database
        self.init_database()

        self.create_main_ui()
    
    def load_config(self):
        """Load configuration from file and decrypt protected values."""
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                config = json.load(f)

            device_fp = get_device_fingerprint()
            if not verify_config_signature(config, device_fp):
                messagebox.showerror(
                    'Configuration Tampered',
                    'Local configuration signature is invalid.\nPlease reinstall or re-run activation.'
                )
                return {}

            config['api_key'] = get_config_value(config, 'api_key_encrypted', device_fp)
            config['company_name'] = get_config_value(config, 'company_name_encrypted', device_fp, 'My Business')
            config['contact_email'] = get_config_value(config, 'contact_email_encrypted', device_fp)
            config['contact_phone'] = get_config_value(config, 'contact_phone_encrypted', device_fp)
            config['business_address'] = get_config_value(config, 'business_address_encrypted', device_fp)
            config['logo_url'] = get_config_value(config, 'logo_url_encrypted', device_fp)
            return config
        return {}
    
    def save_config(self):
        """Save configuration to file with machine-tied api key encryption."""
        persistable = dict(self.config)
        device_fp = get_device_fingerprint()

        for plain_key, encrypted_key in [
            ('api_key', 'api_key_encrypted'),
            ('company_name', 'company_name_encrypted'),
            ('contact_email', 'contact_email_encrypted'),
            ('contact_phone', 'contact_phone_encrypted'),
            ('business_address', 'business_address_encrypted'),
            ('logo_url', 'logo_url_encrypted'),
        ]:
            plain_value = persistable.pop(plain_key, '')
            if plain_value:
                persistable[encrypted_key] = encrypt_config_value(str(plain_value), device_fp)

        persistable['config_signature'] = sign_config(persistable, device_fp)

        with open(CONFIG_FILE, 'w') as f:
            json.dump(persistable, f, indent=2)

    # ------------------------------------------------------------------
    # License validation
    # ------------------------------------------------------------------

    def _is_payment_required_error(self, message, status_code=None):
        normalized = (message or '').strip().lower()
        status_is_payment = status_code in {401, 402, 403}
        text_indicates_expired = any(keyword in normalized for keyword in ['expired', 'renew', 'payment', 'pay'])
        return status_is_payment and text_indicates_expired

    def _show_payment_required_popup(self, details=''):
        popup = tk.Toplevel(self.root)
        popup.title('Subscription Expired')
        popup.configure(bg='white')
        popup.resizable(False, False)

        frame = tk.Frame(popup, bg='white', padx=24, pady=20)
        frame.pack(fill='both', expand=True)

        tk.Label(
            frame,
            text='Your subscription has expired.',
            bg='white',
            fg='#111827',
            font=('Segoe UI', 13, 'bold'),
        ).pack(anchor='w')

        tk.Label(
            frame,
            text='Please complete your payment to continue using this system.',
            bg='white',
            fg='#374151',
            justify='left',
            wraplength=460,
            font=('Segoe UI', 10),
        ).pack(anchor='w', pady=(8, 4))

        if details:
            tk.Label(
                frame,
                text=details,
                bg='white',
                fg='#6b7280',
                justify='left',
                wraplength=460,
                font=('Segoe UI', 9),
            ).pack(anchor='w', pady=(0, 12))

        actions = tk.Frame(frame, bg='white')
        actions.pack(fill='x', pady=(4, 0))

        def _open_payment_portal():
            webbrowser.open(PAYMENT_PORTAL_URL)
            popup.destroy()

        tk.Button(
            actions,
            text='Go To Payment Website',
            command=_open_payment_portal,
            bg='#d97706',
            fg='white',
            activebackground='#b45309',
            activeforeground='white',
            relief='flat',
            padx=14,
            pady=8,
            cursor='hand2',
        ).pack(side='left')

        tk.Button(
            actions,
            text='Close',
            command=popup.destroy,
            bg='#e5e7eb',
            fg='#111827',
            relief='flat',
            padx=14,
            pady=8,
            cursor='hand2',
        ).pack(side='left', padx=(10, 0))

        popup.transient(self.root)
        popup.grab_set()
        popup.focus_force()
        self.root.update_idletasks()
        self.root.wait_window(popup)

    def validate_license(self):
        """Online-first validation with short offline fallback using signed token."""
        api_key = self.config.get('api_key', '')
        if not api_key:
            messagebox.showerror(
                'Configuration Required',
                'No API key found.\nPlease reinstall the application with a valid API key.'
            )
            return False

        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            messagebox.showerror(
                'Remote Verification Required',
                'Remote HTTPS license API is not configured.\nPlease set ZORO9X_PUBLIC_API_URL.'
            )
            return False

        device_fp = get_device_fingerprint()
        device_info = {
            'device_name': platform.node(),
            'os': f'{platform.system()} {platform.release()}',
            'machine': platform.machine(),
            'mac_address': get_mac_address(),
        }
        try:
            resp = requests.post(
                f'{api_url}{VALIDATE_ENDPOINT}',
                json={'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                timeout=10,
            )
            data = resp.json()
            if resp.status_code == 200 and data.get('valid'):
                grace_period_minutes = resolve_grace_period_minutes(data)
                cache_data = {
                    'valid': True,
                    'last_check': datetime.now().isoformat(),
                    'token': data.get('token', ''),
                    'subscription_id': data.get('subscription', {}).get('id'),
                    'device_fingerprint': device_fp,
                    'grace_period_minutes': grace_period_minutes,
                    'grace_period_days': max(1, int((grace_period_minutes + 1439) / 1440)),
                }
                cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                save_license_cache(cache_data)
                self._send_heartbeat(device_fp)
                self._schedule_heartbeat(device_fp)
                return True
            if resp.status_code == 403 and 'not activated' in data.get('message', '').lower():
                return self._activate_device(api_key, device_fp, device_info)
            license_message = data.get('message', 'License validation failed. Please contact support.')
            if self._is_payment_required_error(license_message, resp.status_code):
                self._show_payment_required_popup(license_message)
                return False
            messagebox.showerror(
                'License Error',
                license_message
            )
            return False
        except requests.exceptions.ConnectionError:
            return self._check_offline_grace()
        except Exception:
            return self._check_offline_grace()

    def _activate_device(self, api_key, device_fp, device_info):
        """Register this device with the license server for the first time."""
        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            return False

        try:
            resp = requests.post(
                f'{api_url}{ACTIVATE_ENDPOINT}',
                json={'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                timeout=10,
            )
            data = resp.json()
            if resp.status_code == 200 and data.get('success'):
                grace_period_minutes = resolve_grace_period_minutes(data)
                cache_data = {
                    'valid': True,
                    'last_check': datetime.now().isoformat(),
                    'token': data.get('token', ''),
                    'subscription_id': data.get('subscription', {}).get('id'),
                    'device_fingerprint': device_fp,
                    'grace_period_minutes': grace_period_minutes,
                    'grace_period_days': max(1, int((grace_period_minutes + 1439) / 1440)),
                }
                cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                save_license_cache(cache_data)
                self._send_heartbeat(device_fp)
                self._schedule_heartbeat(device_fp)
                return True
            if resp.status_code == 202:
                messagebox.showinfo(
                    'Activation Pending',
                    'This device is awaiting administrator approval.\n'
                    'You will be able to use the application once approved.\n'
                    'Contact support if this takes more than 24 hours.'
                )
                return False
            messagebox.showerror(
                'Activation Failed',
                data.get('message', 'Device activation failed. Please contact support.')
            )
            return False
        except Exception:
            return self._check_offline_grace()

    def _check_offline_grace(self):
        """Allow temporary offline usage if cached server token is valid."""
        cache = load_license_cache()
        device_fp = get_device_fingerprint()

        if not cache.get('valid'):
            messagebox.showerror(
                'Internet Required',
                'No valid offline token found.\nPlease connect to internet and start again.'
            )
            return False

        if cache.get('device_fingerprint') and cache.get('device_fingerprint') != device_fp:
            messagebox.showerror(
                'License Mismatch',
                'Offline token belongs to another device.\nPlease reconnect to validate this machine.'
            )
            return False

        if not verify_cache_signature(cache, device_fp):
            messagebox.showerror(
                'License Cache Tampered',
                'Local license cache was modified.\nPlease reconnect to obtain a fresh token.'
            )
            return False

        token = cache.get('token', '')
        is_token_valid, token_payload = verify_server_signed_token(token)
        if not is_token_valid:
            messagebox.showerror(
                'Invalid Offline Token',
                'Server token signature validation failed.\nPlease reconnect to refresh your license.'
            )
            return False

        expires_ms = int(token_payload.get('expires', 0) or 0)
        token_device = token_payload.get('device')
        token_sub = token_payload.get('sub_id')
        cache_sub = cache.get('subscription_id')

        if token_device and token_device != device_fp:
            messagebox.showerror(
                'Device Binding Failed',
                'Offline token is not valid for this device.\nPlease reconnect to renew license.'
            )
            return False

        if token_sub and cache_sub and str(token_sub) != str(cache_sub):
            messagebox.showerror(
                'Subscription Binding Failed',
                'Offline token does not match this subscription.\nPlease reconnect to renew license.'
            )
            return False

        if expires_ms and datetime.now().timestamp() * 1000 > expires_ms:
            self._show_payment_required_popup(
                'Stored token has expired. Please connect to internet and renew your subscription.'
            )
            return False

        grace_period_minutes = resolve_grace_period_minutes(cache)
        try:
            last_check = datetime.fromisoformat(cache.get('last_check', '2000-01-01T00:00:00'))
        except Exception:
            messagebox.showerror(
                'License Cache Invalid',
                'Offline cache timestamp is invalid.\nPlease reconnect to refresh your license.'
            )
            return False

        offline_minutes = int((datetime.now() - last_check).total_seconds() // 60)
        if offline_minutes > grace_period_minutes:
            self._show_payment_required_popup(
                f'No server contact for {offline_minutes} minute(s) '
                f'(limit: {grace_period_minutes}). Please reconnect and renew if your plan has expired.'
            )
            return False

        remaining = grace_period_minutes - offline_minutes
        if remaining <= 1:
            messagebox.showwarning(
                'Offline Mode',
                f'Running in offline mode. Internet required within {remaining} minute(s).'
            )

        return True

    def _send_heartbeat(self, device_fp=None):
        api_key = self.config.get('api_key', '')
        if not api_key:
            return

        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            return

        payload = {
            'api_key': api_key,
            'device_fingerprint': device_fp or get_device_fingerprint(),
        }

        try:
            requests.post(f'{api_url}{HEARTBEAT_ENDPOINT}', json=payload, timeout=5)
        except Exception:
            pass

    def _schedule_heartbeat(self, device_fp=None):
        if self.heartbeat_job:
            try:
                self.root.after_cancel(self.heartbeat_job)
            except Exception:
                pass

        def heartbeat_tick():
            self._send_heartbeat(device_fp)
            self.heartbeat_job = self.root.after(60000, heartbeat_tick)

        self.heartbeat_job = self.root.after(60000, heartbeat_tick)

    # ------------------------------------------------------------------

    def init_database(self):
        """Initialize SQLite database with tables"""
        conn = sqlite3.connect(self.db_file)
        cursor = conn.cursor()
        
        # Create records table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        conn.commit()
        conn.close()
    
    def create_main_ui(self):
        """Create main application interface"""
        # Sidebar
        sidebar = tk.Frame(self.root, bg='#2563eb', width=250)
        sidebar.pack(side=tk.LEFT, fill=tk.Y)
        sidebar.pack_propagate(False)
        
        # Logo/Header
        logo_frame = tk.Frame(sidebar, bg='#1d4ed8', height=80)
        logo_frame.pack(fill=tk.X)
        logo_frame.pack_propagate(False)
        
        tk.Label(
            logo_frame,
            text=self.company_name,
            font=('Segoe UI', 16, 'bold'),
            bg='#1d4ed8',
            fg='white',
            wraplength=230
        ).pack(pady=20)
        
        # Navigation
        nav_frame = tk.Frame(sidebar, bg='#2563eb')
        nav_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=20)
        
        nav_btn_0 = tk.Button(
            nav_frame,
            text="📊 Dashboard",
            font=('Segoe UI', 11),
            bg='#2563eb',
            fg='white',
            activebackground='#1d4ed8',
            activeforeground='white',
            relief='flat',
            anchor='w',
            padx=20,
            pady=12,
            cursor='hand2',
            command=self.show_dashboard
        )
        nav_btn_0.pack(fill=tk.X, pady=5)

        nav_btn_1 = tk.Button(
            nav_frame,
            text="📉 Advanced Analytics",
            font=('Segoe UI', 11),
            bg='#2563eb',
            fg='white',
            activebackground='#1d4ed8',
            activeforeground='white',
            relief='flat',
            anchor='w',
            padx=20,
            pady=12,
            cursor='hand2',
            command=self.show_advanced_analytics
        )
        nav_btn_1.pack(fill=tk.X, pady=5)

        nav_btn_2 = tk.Button(
            nav_frame,
            text="📈 Custom Reports",
            font=('Segoe UI', 11),
            bg='#2563eb',
            fg='white',
            activebackground='#1d4ed8',
            activeforeground='white',
            relief='flat',
            anchor='w',
            padx=20,
            pady=12,
            cursor='hand2',
            command=self.show_custom_reports
        )
        nav_btn_2.pack(fill=tk.X, pady=5)
        
        # Logout button
        tk.Button(
            sidebar,
            text="🚪 Logout",
            font=('Segoe UI', 11),
            bg='#dc2626',
            fg='white',
            relief='flat',
            padx=20,
            pady=10,
            cursor='hand2',
            command=self.logout
        ).pack(side=tk.BOTTOM, pady=20, padx=10, fill=tk.X)
        
        # Content area
        self.content_frame = tk.Frame(self.root, bg='#f5f7fa')
        self.content_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)
        
        # Header
        header = tk.Frame(self.content_frame, bg='white', height=60)
        header.pack(fill=tk.X)
        header.pack_propagate(False)
        
        tk.Label(
            header,
            text="Gold Loan System",
            font=('Segoe UI', 18, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack(side=tk.LEFT, padx=30, pady=15)
        
        tk.Label(
            header,
            text=datetime.now().strftime("%B %d, %Y"),
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack(side=tk.RIGHT, padx=30)
        
        # Show dashboard
        self.show_dashboard()
    
    def show_dashboard(self):
        """Display dashboard view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        dashboard_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        dashboard_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            dashboard_frame,
            text="📊 Dashboard",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Stats cards
        stats_frame = tk.Frame(dashboard_frame, bg='#f5f7fa')
        stats_frame.pack(fill=tk.X, pady=10)
        
        self.create_stat_card(stats_frame, "📝 Total Records", "0", "#3b82f6")
        self.create_stat_card(stats_frame, "✅ Active", "0", "#10b981")
        self.create_stat_card(stats_frame, "⏰ Pending", "0", "#f59e0b")
        
        # Welcome message
        tk.Label(
            dashboard_frame,
            text=f"Welcome to {self.company_name}!",
            font=('Segoe UI', 14),
            bg='#f5f7fa',
            fg='#475569'
        ).pack(pady=30)
    
    def create_stat_card(self, parent, title, value, color):
        """Create a statistics card"""
        card = tk.Frame(parent, bg='white', relief=tk.SOLID, bd=1)
        card.pack(side=tk.LEFT, padx=10, ipadx=30, ipady=20)
        card.config(highlightbackground='#e2e8f0', highlightthickness=1)
        
        icon_frame = tk.Frame(card, bg=color, width=50, height=50)
        icon_frame.pack(pady=(0, 10))
        icon_frame.pack_propagate(False)
        
        tk.Label(
            card,
            text=title,
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack()
        
        tk.Label(
            card,
            text=value,
            font=('Segoe UI', 24, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack()
    
    def show_dashboard(self):
        """Display Dashboard view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        view_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        view_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            view_frame,
            text="📊 Dashboard",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Add your Dashboard functionality here
        tk.Label(
            view_frame,
            text="Dashboard feature coming soon!",
            font=('Segoe UI', 12),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=50)

        
        # Premium Feature: Advanced Analytics
        premium_frame = tk.Frame(view_frame, bg='#fef3c7', relief=tk.SOLID, bd=1)
        premium_frame.pack(fill=tk.X, pady=10, padx=20, ipady=10)
        
        tk.Label(
            premium_frame,
            text="⭐ Premium Feature",
            font=('Segoe UI', 10, 'bold'),
            bg='#fef3c7',
            fg='#92400e'
        ).pack(pady=5)

    def show_advanced_analytics(self):
        """Display Advanced Analytics view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        view_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        view_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            view_frame,
            text="📉 Advanced Analytics",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Add your Advanced Analytics functionality here
        tk.Label(
            view_frame,
            text="Advanced Analytics feature coming soon!",
            font=('Segoe UI', 12),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=50)

        
        # Premium Feature: Advanced Analytics
        premium_frame = tk.Frame(view_frame, bg='#fef3c7', relief=tk.SOLID, bd=1)
        premium_frame.pack(fill=tk.X, pady=10, padx=20, ipady=10)
        
        tk.Label(
            premium_frame,
            text="⭐ Premium Feature",
            font=('Segoe UI', 10, 'bold'),
            bg='#fef3c7',
            fg='#92400e'
        ).pack(pady=5)

    def show_custom_reports(self):
        """Display Custom Reports view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        view_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        view_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            view_frame,
            text="📈 Custom Reports",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Add your Custom Reports functionality here
        tk.Label(
            view_frame,
            text="Custom Reports feature coming soon!",
            font=('Segoe UI', 12),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=50)

        
        # Premium Feature: Advanced Analytics
        premium_frame = tk.Frame(view_frame, bg='#fef3c7', relief=tk.SOLID, bd=1)
        premium_frame.pack(fill=tk.X, pady=10, padx=20, ipady=10)
        
        tk.Label(
            premium_frame,
            text="⭐ Premium Feature",
            font=('Segoe UI', 10, 'bold'),
            bg='#fef3c7',
            fg='#92400e'
        ).pack(pady=5)
    
    def logout(self):
        """Logout and close application"""
        if messagebox.askyesno("Logout", "Are you sure you want to logout?"):
            self.root.quit()
    
    def run(self):
        """Run the application"""
        self.root.mainloop()


if __name__ == '__main__':
    app = GoldLoanSystemApp()
    app.run()
