/**
 * Migration: Add admin subscription event types to audit_logs.event_type ENUM
 * 
 * This migration updates the audit_logs table to include the new event types
 * that are generated by admin subscription management actions.
 */

const { pool } = require('../config/database');

async function updateAuditLogsEnum() {
  const connection = await pool.getConnection();
  try {
    console.log('🔄 Migrating audit_logs table...');

    // Alter the event_type ENUM to include new admin event types
    const alterQuery = `
      ALTER TABLE audit_logs
      MODIFY COLUMN event_type ENUM(
        'download',
        'activation_approved',
        'activation_pending',
        'activation_rejected',
        'revocation',
        'token_refresh',
        'validation_blocked',
        'policy_violation',
        'approval',
        'rejection',
        'business_info_change_requested',
        'business_info_change_approved',
        'business_info_change_rejected',
        'admin_subscription_activate',
        'admin_subscription_deactivate',
        'admin_subscription_expire',
        'admin_subscription_extend_days',
        'admin_subscription_set_end_date',
        'admin_subscription_lifetime',
        'admin_subscription_set_activation'
      ) NOT NULL
    `;

    await connection.execute(alterQuery);
    console.log('✅ audit_logs.event_type ENUM successfully updated with admin event types');

    connection.release();
    return true;
  } catch (error) {
    console.error('❌ Error updating audit_logs ENUM:', error.message);
    connection.release();
    throw error;
  }
}

module.exports = {
  updateAuditLogsEnum,
};

// Run if called directly
if (require.main === module) {
  updateAuditLogsEnum()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
