"""
Gold Loan System - BASIC Edition
Auto-generated by ZORO9X SaaS Platform
"""

import tkinter as tk
from tkinter import ttk, messagebox
import sqlite3
import json
import os
import traceback
import hashlib
import platform
import uuid
import requests
import webbrowser
from datetime import datetime
import base64
import sys
import hmac
import urllib3
import threading
from theme import GOLD_THEME
from backup_manager import get_backup_manager

# Configuration
APP_DIR = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(APP_DIR, 'gold_loan_config.json')
LICENSE_CACHE_FILE = os.path.join(APP_DIR, 'gold_loan_license.json')
SERVER_API_URL_FILE = os.path.join(APP_DIR, 'server_api_url.txt')
DEFAULT_LOCAL_LOGO_PATH = os.path.join(APP_DIR, 'logo.png')
DEFAULT_OFFLINE_GRACE_DAYS = max(1, int(os.getenv('ZORO9X_OFFLINE_GRACE_DAYS', '7')))
API_URL = 'https://www.zoro9x.com'
PAYMENT_PORTAL_URL = f'{API_URL}/client-dashboard'
VALIDATE_ENDPOINT = '/api/saas/validate-key'
ACTIVATE_ENDPOINT = '/api/saas/activate-device'
HEARTBEAT_ENDPOINT = '/api/saas/heartbeat'
SHUTDOWN_ENDPOINT = '/api/saas/shutdown'
TOKEN_VERIFY_SECRET = 'your_jwt_secret_key_change_this_in_production_12345678'
CONFIG_SIGNING_SECRET = 'your_jwt_secret_key_change_this_in_production_12345678'
DEV_BYPASS_ENV = 'ZORO9X_DEV_BYPASS_LICENSE'
VALIDATION_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_VALIDATE_TIMEOUT_SECONDS', '4'))
ACTIVATION_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_ACTIVATE_TIMEOUT_SECONDS', '4'))
HEARTBEAT_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_HEARTBEAT_TIMEOUT_SECONDS', '1.5'))
SHUTDOWN_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_SHUTDOWN_TIMEOUT_SECONDS', '0.8'))
MAX_FALLBACK_API_URLS = max(1, int(os.getenv('ZORO9X_MAX_API_FALLBACKS', '2')))


def get_effective_api_url():
    env_url = os.getenv('ZORO9X_PUBLIC_API_URL', '').strip()
    if is_remote_api_url(env_url):
        return env_url.rstrip('/')

    if os.path.exists(SERVER_API_URL_FILE):
        try:
            with open(SERVER_API_URL_FILE, 'r', encoding='utf-8') as f:
                file_url = (f.read() or '').strip()
            if is_remote_api_url(file_url):
                return file_url.rstrip('/')
        except Exception:
            pass

    return API_URL.rstrip('/')


def build_api_url_candidates():
    ordered = []

    def _add(url):
        normalized = (url or '').strip().rstrip('/')
        if is_remote_api_url(normalized) and normalized not in ordered:
            ordered.append(normalized)

    _add(os.getenv('ZORO9X_PUBLIC_API_URL', ''))

    if os.path.exists(SERVER_API_URL_FILE):
        try:
            with open(SERVER_API_URL_FILE, 'r', encoding='utf-8') as f:
                _add(f.read())
        except Exception:
            pass

    _add(API_URL)
    _add('http://127.0.0.1:5001')
    _add('http://localhost:5001')

    for base in list(ordered):
        if base.startswith('https://www.'):
            _add('https://' + base[len('https://www.'):])
        elif base.startswith('https://'):
            _add('https://www.' + base[len('https://'):])

    return ordered


def post_with_tls_fallback(url, payload, timeout=10):
    try:
        return requests.post(url, json=payload, timeout=timeout)
    except requests.exceptions.SSLError:
        # Some environments perform TLS interception; retry once without strict verification.
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        return requests.post(url, json=payload, timeout=timeout, verify=False)


def is_license_bypass_enabled():
    bypass_requested = os.getenv(DEV_BYPASS_ENV, '').strip().lower() in {'1', 'true', 'yes', 'on'}
    running_packaged = bool(getattr(sys, 'frozen', False))
    return bypass_requested and not running_packaged


def is_remote_api_url(url):
    normalized = (url or '').strip().lower()
    return bool(normalized and (normalized.startswith('http://') or normalized.startswith('https://')))


def xor_bytes(data, key_material):
    key = hashlib.sha256(key_material.encode()).digest()
    return bytes(byte ^ key[index % len(key)] for index, byte in enumerate(data))


def encrypt_config_value(value, device_fp):
    if not value:
        return ''
    encrypted = xor_bytes(value.encode('utf-8'), f'config:{device_fp}')
    return base64.b64encode(encrypted).decode('utf-8')


def decrypt_config_value(value, device_fp):
    if not value:
        return ''
    try:
        decoded = base64.b64decode(value.encode('utf-8'))
        decrypted = xor_bytes(decoded, f'config:{device_fp}')
        return decrypted.decode('utf-8')
    except Exception:
        return value


def get_config_value(config, encrypted_key, device_fp, default=''):
    encrypted_value = config.get(encrypted_key, '')
    if encrypted_value:
        return decrypt_config_value(encrypted_value, device_fp)
    return default


def sign_config(config_data, device_fp):
    signable = {
        'api_key_encrypted': config_data.get('api_key_encrypted', ''),
        'company_name_encrypted': config_data.get('company_name_encrypted', ''),
        'contact_email_encrypted': config_data.get('contact_email_encrypted', ''),
        'contact_phone_encrypted': config_data.get('contact_phone_encrypted', ''),
        'business_address_encrypted': config_data.get('business_address_encrypted', ''),
        'logo_url_encrypted': config_data.get('logo_url_encrypted', ''),
        'database_name': config_data.get('database_name', ''),
        'database_path': config_data.get('database_path', ''),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        CONFIG_SIGNING_SECRET.encode('utf-8'),
        f'config:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_config_signature(config_data, device_fp):
    expected = sign_config(config_data, device_fp)
    provided = config_data.get('config_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def get_device_fingerprint():
    raw = '|'.join([platform.node(), platform.machine(), str(uuid.getnode())])
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


def get_mac_address():
    mac_num = uuid.getnode()
    mac_hex = f'{mac_num:012x}'
    return ':'.join(mac_hex[i:i+2] for i in range(0, 12, 2))


def parse_token_payload(token):
    try:
        if not token or '.' not in token:
            return {}
        payload_part = token.split('.', 1)[0]
        payload_part += '=' * (-len(payload_part) % 4)
        raw = base64.b64decode(payload_part.encode())
        return json.loads(raw.decode())
    except Exception:
        return {}


def verify_server_signed_token(token):
    try:
        if not token or '.' not in token:
            return False, {}
        payload_part, signature = token.split('.', 1)
        if not payload_part or not signature:
            return False, {}
        expected = hmac.new(
            TOKEN_VERIFY_SECRET.encode('utf-8'),
            payload_part.encode('utf-8'),
            hashlib.sha256,
        ).hexdigest()
        if not hmac.compare_digest(signature, expected):
            return False, {}
        payload = parse_token_payload(token)
        return bool(payload), payload
    except Exception:
        return False, {}


def resolve_grace_period_days(payload):
    try:
        grace_days = int(payload.get('grace_period_days') or DEFAULT_OFFLINE_GRACE_DAYS)
    except Exception:
        grace_days = DEFAULT_OFFLINE_GRACE_DAYS

    return max(1, grace_days)


def sign_cache(cache_data, device_fp):
    signable = {
        'valid': cache_data.get('valid', False),
        'last_check': cache_data.get('last_check', ''),
        'token': cache_data.get('token', ''),
        'subscription_id': cache_data.get('subscription_id'),
        'device_fingerprint': cache_data.get('device_fingerprint', ''),
        'grace_period_days': cache_data.get('grace_period_days', DEFAULT_OFFLINE_GRACE_DAYS),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        TOKEN_VERIFY_SECRET.encode('utf-8'),
        f'cache:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_cache_signature(cache_data, device_fp):
    expected = sign_cache(cache_data, device_fp)
    provided = cache_data.get('cache_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def load_license_cache():
    if os.path.exists(LICENSE_CACHE_FILE):
        try:
            with open(LICENSE_CACHE_FILE, 'r') as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_license_cache(data):
    try:
        with open(LICENSE_CACHE_FILE, 'w') as f:
            json.dump(data, f, indent=2)
    except Exception:
        pass


class GoldLoanSystemApp:
    def __init__(self):
        self.root = tk.Tk()
        GOLD_THEME.apply_window(
            self.root,
            min_size=(1024, 680),
            size=(1360, 820),
            title='Gold Loan System - Basic Edition',
            maximize=True,
        )
        self._set_window_icon()
        self.theme = GOLD_THEME
        self.current_user = None
        self.heartbeat_job = None

        # Load configuration
        self.config = self.load_config()

        # Database configuration
        db_name = self.config.get('database_name', 'gold_loan_basic_database')
        db_path = self.config.get('database_path', f'{db_name}.db')
        self.db_file = db_path if os.path.isabs(db_path) else os.path.join(APP_DIR, db_path)

        self.company_name = self.config.get('company_name', 'My Business')

        # Validate license before allowing access
        if not self.validate_license():
            self.root.destroy()
            return

        # Initialize database
        from database import init_database, set_setting, set_db_file
        set_db_file(self.db_file)
        init_database(self.db_file)

        # Initialize backup manager
        try:
            db_dir = os.path.dirname(self.db_file)
            self.backup_manager = get_backup_manager(db_dir)
            # Create initial backup on app start
            self.backup_manager.create_backup_and_queue()
            self.backup_manager.sync_pending_uploads()
        except Exception as e:
            print(f"Warning: Backup manager initialization failed: {e}")
            self.backup_manager = None

        # Keep core company identity fields aligned with signed downloaded config.
        # These values are managed by subscription profile and should not drift locally.
        managed_company_fields = {
            'company_name': 'company_name',
            'company_phone': 'contact_phone',
            'company_address': 'business_address',
        }
        for setting_key, config_key in managed_company_fields.items():
            value = (self.config.get(config_key, '') or '').strip()
            if value:
                set_setting(setting_key, value, user_id=None, db_path=self.db_file)

        logo_url = (self.config.get('logo_url', '') or '').strip()
        if logo_url:
            set_setting('company_logo_url', logo_url, user_id=None, db_path=self.db_file)

        if os.path.exists(DEFAULT_LOCAL_LOGO_PATH):
            set_setting('company_logo_path', DEFAULT_LOCAL_LOGO_PATH, user_id=None, db_path=self.db_file)

        # Register app close handler for backup
        self.root.protocol('WM_DELETE_WINDOW', self._on_closing)

        # Show login
        self._show_login()

    def _set_window_icon(self):
        bundle_dir = getattr(sys, '_MEIPASS', '') if getattr(sys, 'frozen', False) else ''
        icon_candidates = [
            os.path.join(APP_DIR, 'logo.ico'),
            os.path.join(APP_DIR, 'app.ico'),
        ]
        if bundle_dir:
            icon_candidates.extend([
                os.path.join(bundle_dir, 'logo.ico'),
                os.path.join(bundle_dir, 'app.ico'),
            ])
        for icon_path in icon_candidates:
            if os.path.exists(icon_path):
                try:
                    self.root.iconbitmap(icon_path)
                    return
                except Exception:
                    pass

        logo_png_candidates = [
            DEFAULT_LOCAL_LOGO_PATH,
            os.path.join(APP_DIR, 'pawn_ticket', 'pms_logo.png'),
        ]
        if bundle_dir:
            logo_png_candidates.append(os.path.join(bundle_dir, 'logo.png'))
        for logo_path in logo_png_candidates:
            if os.path.exists(logo_path):
                try:
                    self._window_icon_image = tk.PhotoImage(file=logo_path)
                    self.root.iconphoto(True, self._window_icon_image)
                    return
                except Exception:
                    pass

    def load_config(self):
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                config = json.load(f)
            device_fp = get_device_fingerprint()
            if not verify_config_signature(config, device_fp):
                messagebox.showerror(
                    'Configuration Tampered',
                    'Local configuration signature is invalid.\nPlease reinstall or re-run activation.'
                )
                return {}
            config['api_key'] = get_config_value(config, 'api_key_encrypted', device_fp)
            config['company_name'] = get_config_value(config, 'company_name_encrypted', device_fp, 'My Business')
            config['contact_email'] = get_config_value(config, 'contact_email_encrypted', device_fp)
            config['contact_phone'] = get_config_value(config, 'contact_phone_encrypted', device_fp)
            config['business_address'] = get_config_value(config, 'business_address_encrypted', device_fp)
            config['logo_url'] = get_config_value(config, 'logo_url_encrypted', device_fp)
            return config
        return {}

    # ------------------------------------------------------------------
    # License validation (preserved from original)
    # ------------------------------------------------------------------

    def _is_payment_required_error(self, message, status_code=None):
        normalized = (message or '').strip().lower()
        status_is_payment = status_code in {401, 402, 403}
        text_indicates_expired = any(keyword in normalized for keyword in ['expired', 'renew', 'payment', 'pay'])
        return status_is_payment and text_indicates_expired

    def _show_payment_required_popup(self, details=''):
        popup = tk.Toplevel(self.root)
        popup.title('Subscription Expired')
        popup.configure(bg='white')
        popup.resizable(False, False)

        frame = tk.Frame(popup, bg='white', padx=24, pady=20)
        frame.pack(fill='both', expand=True)

        tk.Label(
            frame,
            text='Your subscription has expired.',
            bg='white',
            fg='#111827',
            font=('Segoe UI', 13, 'bold'),
        ).pack(anchor='w')

        tk.Label(
            frame,
            text='Please complete your payment to continue using this system.',
            bg='white',
            fg='#374151',
            justify='left',
            wraplength=460,
            font=('Segoe UI', 10),
        ).pack(anchor='w', pady=(8, 4))

        if details:
            tk.Label(
                frame,
                text=details,
                bg='white',
                fg='#6b7280',
                justify='left',
                wraplength=460,
                font=('Segoe UI', 9),
            ).pack(anchor='w', pady=(0, 12))

        actions = tk.Frame(frame, bg='white')
        actions.pack(fill='x', pady=(4, 0))

        def _open_payment_portal():
            webbrowser.open(PAYMENT_PORTAL_URL)
            popup.destroy()

        tk.Button(
            actions,
            text='Go To Payment Website',
            command=_open_payment_portal,
            bg='#d97706',
            fg='white',
            activebackground='#b45309',
            activeforeground='white',
            relief='flat',
            padx=14,
            pady=8,
            cursor='hand2',
        ).pack(side='left')

        tk.Button(
            actions,
            text='Close',
            command=popup.destroy,
            bg='#e5e7eb',
            fg='#111827',
            relief='flat',
            padx=14,
            pady=8,
            cursor='hand2',
        ).pack(side='left', padx=(10, 0))

        popup.transient(self.root)
        popup.grab_set()
        popup.focus_force()
        self.root.update_idletasks()
        self.root.wait_window(popup)

    def validate_license(self):
        if is_license_bypass_enabled():
            messagebox.showwarning(
                'Development Mode',
                f'License validation is bypassed because {DEV_BYPASS_ENV}=1.\n'
                'Use this only for local development.'
            )
            return True

        api_key = self.config.get('api_key', '')
        if not api_key:
            messagebox.showerror(
                'Configuration Required',
                'No API key found.\nPlease reinstall the application with a valid API key.'
            )
            return False

        api_urls = build_api_url_candidates()[:MAX_FALLBACK_API_URLS]
        if not api_urls:
            messagebox.showerror(
                'Remote Verification Required',
                'Remote HTTPS license API is not configured.\nPlease set ZORO9X_PUBLIC_API_URL.'
            )
            return False

        device_fp = get_device_fingerprint()
        device_info = {
            'device_name': platform.node(),
            'os': f'{platform.system()} {platform.release()}',
            'machine': platform.machine(),
            'mac_address': get_mac_address(),
        }
        had_network_exception = False
        last_exception = None

        for api_url in api_urls:
            try:
                resp = post_with_tls_fallback(
                    f'{api_url}{VALIDATE_ENDPOINT}',
                    {'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                    timeout=VALIDATION_TIMEOUT_SECONDS,
                )
                data = resp.json()
                if resp.status_code == 200 and data.get('valid'):
                    grace_period_days = resolve_grace_period_days(data)
                    cache_data = {
                        'valid': True,
                        'last_check': datetime.now().isoformat(),
                        'token': data.get('token', ''),
                        'subscription_id': data.get('subscription', {}).get('id'),
                        'device_fingerprint': device_fp,
                        'grace_period_days': grace_period_days,
                    }
                    cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                    save_license_cache(cache_data)
                    self._send_heartbeat(device_fp)
                    self._schedule_heartbeat(device_fp)
                    return True

                if resp.status_code == 403 and 'not activated' in data.get('message', '').lower():
                    return self._activate_device(api_key, device_fp, device_info)

                license_message = data.get('message', 'License validation failed. Please contact support.')
                if self._is_payment_required_error(license_message, resp.status_code):
                    self._show_payment_required_popup(license_message)
                    return False

                if resp.status_code < 500:
                    messagebox.showerror('License Error', license_message)
                    return False

                had_network_exception = True
            except requests.exceptions.ConnectionError as exc:
                had_network_exception = True
                last_exception = exc
            except Exception as exc:
                had_network_exception = True
                last_exception = exc

        if had_network_exception:
            return self._check_offline_grace()

        if last_exception:
            messagebox.showerror('License Error', f'Unable to validate license: {last_exception}')
        return False

    def _activate_device(self, api_key, device_fp, device_info):
        api_urls = build_api_url_candidates()[:MAX_FALLBACK_API_URLS]
        if not api_urls:
            return False
        had_network_exception = False
        last_exception = None

        for api_url in api_urls:
            try:
                resp = post_with_tls_fallback(
                    f'{api_url}{ACTIVATE_ENDPOINT}',
                    {'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                    timeout=ACTIVATION_TIMEOUT_SECONDS,
                )
                data = resp.json()
                if resp.status_code == 200 and data.get('success'):
                    grace_period_days = resolve_grace_period_days(data)
                    cache_data = {
                        'valid': True,
                        'last_check': datetime.now().isoformat(),
                        'token': data.get('token', ''),
                        'subscription_id': data.get('subscription', {}).get('id'),
                        'device_fingerprint': device_fp,
                        'grace_period_days': grace_period_days,
                    }
                    cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                    save_license_cache(cache_data)
                    self._send_heartbeat(device_fp)
                    self._schedule_heartbeat(device_fp)
                    return True
                if resp.status_code == 202:
                    messagebox.showinfo(
                        'Activation Pending',
                        'This device is awaiting administrator approval.\n'
                        'You will be able to use the application once approved.\n'
                        'Contact support if this takes more than 24 hours.'
                    )
                    return False
                if resp.status_code < 500:
                    messagebox.showerror(
                        'Activation Failed',
                        data.get('message', 'Device activation failed. Please contact support.')
                    )
                    return False
                had_network_exception = True
            except Exception as exc:
                had_network_exception = True
                last_exception = exc

        if had_network_exception:
            return self._check_offline_grace()

        if last_exception:
            messagebox.showerror('Activation Failed', f'Unable to activate device: {last_exception}')
        return False

    def _check_offline_grace(self):
        cache = load_license_cache()
        device_fp = get_device_fingerprint()
        if not cache.get('valid'):
            messagebox.showerror('Internet Required',
                                 'No valid offline token found.\nPlease connect to internet and start again.')
            return False
        if cache.get('device_fingerprint') and cache.get('device_fingerprint') != device_fp:
            messagebox.showerror('License Mismatch',
                                 'Offline token belongs to another device.\nPlease reconnect to validate this machine.')
            return False
        if not verify_cache_signature(cache, device_fp):
            messagebox.showerror('License Cache Tampered',
                                 'Local license cache was modified.\nPlease reconnect to obtain a fresh token.')
            return False
        token = cache.get('token', '')
        is_token_valid, token_payload = verify_server_signed_token(token)
        if not is_token_valid:
            messagebox.showerror('Invalid Offline Token',
                                 'Server token signature validation failed.\nPlease reconnect to refresh your license.')
            return False
        expires_ms = int(token_payload.get('expires', 0) or 0)
        token_device = token_payload.get('device')
        token_sub = token_payload.get('sub_id')
        cache_sub = cache.get('subscription_id')
        if token_device and token_device != device_fp:
            messagebox.showerror('Device Binding Failed',
                                 'Offline token is not valid for this device.\nPlease reconnect to renew license.')
            return False
        if token_sub and cache_sub and str(token_sub) != str(cache_sub):
            messagebox.showerror('Subscription Binding Failed',
                                 'Offline token does not match this subscription.\nPlease reconnect to renew license.')
            return False
        if expires_ms and datetime.now().timestamp() * 1000 > expires_ms:
            self._show_payment_required_popup(
                'Stored token has expired. Please connect to internet and renew your subscription.'
            )
            return False
        grace_period_days = resolve_grace_period_days(cache)
        try:
            last_check = datetime.fromisoformat(cache.get('last_check', '2000-01-01T00:00:00'))
        except Exception:
            messagebox.showerror('License Cache Invalid',
                                 'Offline cache timestamp is invalid.\nPlease reconnect to refresh your license.')
            return False
        offline_days = max(0, int((datetime.now() - last_check).total_seconds() // (60 * 60 * 24)))

        if offline_days > grace_period_days:
            self._show_payment_required_popup(
                f'No server contact for {offline_days} day(s) '
                f'(limit: {grace_period_days}). Please reconnect and renew if your plan has expired.'
            )
            return False

        remaining_days = grace_period_days - offline_days
        messagebox.showwarning(
            'Offline Mode',
            f'Application started in offline mode. Internet required within {remaining_days} day(s).'
        )
        return True

    def _send_heartbeat(self, device_fp=None):
        api_key = self.config.get('api_key', '')
        if not api_key:
            return

        api_urls = build_api_url_candidates()[:MAX_FALLBACK_API_URLS]
        if not api_urls:
            return

        payload = {
            'api_key': api_key,
            'device_fingerprint': device_fp or get_device_fingerprint(),
        }

        for api_url in api_urls:
            try:
                resp = post_with_tls_fallback(f'{api_url}{HEARTBEAT_ENDPOINT}', payload, timeout=HEARTBEAT_TIMEOUT_SECONDS)
                if resp.status_code == 200:
                    return
            except Exception:
                continue

    def _send_shutdown(self, device_fp=None):
        api_key = self.config.get('api_key', '')
        if not api_key:
            return

        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            return

        payload = {
            'api_key': api_key,
            'device_fingerprint': device_fp or get_device_fingerprint(),
        }

        try:
            post_with_tls_fallback(f'{api_url}{SHUTDOWN_ENDPOINT}', payload, timeout=SHUTDOWN_TIMEOUT_SECONDS)
        except Exception:
            pass

    def _schedule_heartbeat(self, device_fp=None):
        if self.heartbeat_job:
            try:
                self.root.after_cancel(self.heartbeat_job)
            except Exception:
                pass

        def heartbeat_tick():
            self._send_heartbeat(device_fp)
            self.heartbeat_job = self.root.after(60000, heartbeat_tick)

        self.heartbeat_job = self.root.after(60000, heartbeat_tick)

    # ------------------------------------------------------------------
    # Application UI
    # ------------------------------------------------------------------

    def _show_login(self):
        """Show login screen."""
        # Clear root
        for w in self.root.winfo_children():
            w.destroy()

        from pages.login import LoginPage
        self.login_page = LoginPage(self.root, self.theme, self._on_login_success)
        self.login_page.show()

    def _on_login_success(self, user):
        """Handle successful login."""
        try:
            self.current_user = user
            self.login_page.hide()
            self._build_main_ui()
        except Exception as error:
            traceback.print_exc()
            messagebox.showerror(
                'Application Error',
                f'Login succeeded, but loading the dashboard failed.\n\n{error}'
            )
            self._show_login()

    def _build_main_ui(self):
        """Build the main application UI with sidebar navigation."""
        for w in self.root.winfo_children():
            w.destroy()

        # Sidebar
        sidebar = tk.Frame(self.root, bg=self.theme.palette.bg_sidebar, width=250)
        sidebar.pack(side=tk.LEFT, fill=tk.Y)
        sidebar.pack_propagate(False)

        from database import get_setting

        # Logo/Header
        logo_card = self.theme.make_card(sidebar, bg=self.theme.palette.bg_surface, border=self.theme.palette.border)
        logo_card.pack(fill=tk.X, padx=12, pady=(12, 10))
        logo_frame = tk.Frame(logo_card.inner, bg=self.theme.palette.bg_surface, height=110)
        logo_frame.pack(fill=tk.X)
        logo_frame.pack_propagate(False)

        logo_path_candidates = [
            DEFAULT_LOCAL_LOGO_PATH,
            os.path.join(APP_DIR, 'pawn_ticket', 'pms_logo.png'),
        ]
        for logo_path in logo_path_candidates:
            if not os.path.exists(logo_path):
                continue
            try:
                self.sidebar_logo_image = tk.PhotoImage(file=logo_path)
                max_dimension = max(self.sidebar_logo_image.width(), self.sidebar_logo_image.height())
                shrink_factor = max(1, int(max_dimension / 36))
                if shrink_factor > 1:
                    self.sidebar_logo_image = self.sidebar_logo_image.subsample(shrink_factor, shrink_factor)
                tk.Label(
                    logo_frame,
                    image=self.sidebar_logo_image,
                    bg=self.theme.palette.bg_surface,
                ).pack(pady=(8, 2))
                break
            except Exception:
                continue

        company_name = get_setting('company_name', 'Gold Loan System') or 'Gold Loan System'

        tk.Label(
            logo_frame, text=company_name,
            font=self.theme.fonts.h3, bg=self.theme.palette.bg_surface,
            fg=self.theme.palette.text_primary, wraplength=230
        ).pack(pady=(4, 2))

        tk.Label(
            logo_frame, text=f'{self.current_user["full_name"]} ({self.current_user["role"].upper()})',
            font=self.theme.fonts.small, bg=self.theme.palette.bg_surface,
            fg=self.theme.palette.text_muted,
        ).pack()

        # Navigation
        nav_frame = tk.Frame(sidebar, bg=self.theme.palette.bg_sidebar)
        nav_frame.pack(fill=tk.BOTH, expand=True, padx=12, pady=8)

        nav_items = [
            ('📊 Dashboard', 'dashboard'),
            ('📝 New Loan', 'new_ticket'),
            ('🔍 Loans', 'loan_list'),
            ('👥 Customers', 'customers'),
        ]

        if self.current_user['role'] == 'admin':
            nav_items.append(('✉️ Letters', 'letters'))
            nav_items.append((' Reports', 'reports'))
            nav_items.append(('⚙️ Admin Settings', 'admin_settings'))
            # Show pending count badge
            from database import get_pending_approval_requests
            pending = get_pending_approval_requests()
            badge = f' ({len(pending)})' if pending else ''
            nav_items.append((f'🔐 Approvals{badge}', 'loan_approvals'))

        self.nav_buttons = {}
        for text, page in nav_items:
            btn = self.theme.make_button(
                nav_frame, text=text, command=lambda p=page: self.navigate(p),
                kind='ghost', width=22, pady=8, align='w',
            )
            btn.pack(fill=tk.X, pady=3)
            self.nav_buttons[page] = btn

        # Logout button
        logout_btn = self.theme.make_button(
            sidebar, text='🚪 Logout', command=self._logout,
            kind='danger', width=20, pady=8,
        )
        logout_btn.pack(side=tk.BOTTOM, pady=14, padx=12, fill=tk.X)

        developer_btn = self.theme.make_button(
            sidebar,
            text='ZORO9X',
            command=lambda: webbrowser.open('https://www.zoro9x.com'),
            kind='ghost',
            width=20,
            pady=8,
        )
        developer_btn.pack(side=tk.BOTTOM, pady=(0, 6), padx=12, fill=tk.X)

        # Content area
        content_outer = tk.Frame(self.root, bg=self.theme.palette.bg_app)
        content_outer.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)

        # Header bar
        header = tk.Frame(content_outer, bg=self.theme.palette.bg_header, height=58)
        header.pack(fill=tk.X, padx=14, pady=(14, 8))
        header.pack_propagate(False)
        header.config(highlightthickness=1, highlightbackground=self.theme.palette.border)

        self.header_label = tk.Label(
            header, text='Dashboard', font=self.theme.fonts.h2,
            bg=self.theme.palette.bg_header, fg=self.theme.palette.text_primary
        )
        self.header_label.pack(side=tk.LEFT, padx=20, pady=12)

        tk.Label(
            header, text=datetime.now().strftime("%B %d, %Y"),
            font=self.theme.fonts.body, bg=self.theme.palette.bg_header,
            fg=self.theme.palette.text_muted
        ).pack(side=tk.RIGHT, padx=20)

        # Scrollable body
        body_host = tk.Frame(content_outer, bg=self.theme.palette.bg_app)
        body_host.pack(fill=tk.BOTH, expand=True, padx=14, pady=(0, 14))
        self._create_scrollable_body(body_host)

        # Show dashboard
        self.navigate('dashboard')

    def _create_scrollable_body(self, parent):
        self.page_canvas = tk.Canvas(
            parent, bg=self.theme.palette.bg_app, highlightthickness=0, bd=0,
        )
        self.page_scrollbar = self.theme.make_scrollbar(parent, self.page_canvas.yview)
        self.page_content = tk.Frame(self.page_canvas, bg=self.theme.palette.bg_app)

        self.page_window_id = self.page_canvas.create_window((0, 0), window=self.page_content, anchor='nw')
        self.page_canvas.configure(yscrollcommand=self.page_scrollbar.set)

        self.page_canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self.page_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self.page_content.bind('<Configure>',
                               lambda event: self.page_canvas.configure(scrollregion=self.page_canvas.bbox('all')))
        self.page_canvas.bind('<Configure>', self._sync_page_width)

        def _on_mousewheel(event):
            self.page_canvas.yview_scroll(int(-1 * (event.delta / 120)), 'units')

        self.root.bind_all('<MouseWheel>', _on_mousewheel)
        self.root.bind_all('<Button-4>', lambda _e: self.page_canvas.yview_scroll(-1, 'units'))
        self.root.bind_all('<Button-5>', lambda _e: self.page_canvas.yview_scroll(1, 'units'))

    def _sync_page_width(self, event):
        self.page_canvas.itemconfig(self.page_window_id, width=event.width)

    def navigate(self, page_name, param=None):
        """Navigate to a page."""
        # Refresh pending approvals badge for admin
        if self.current_user and self.current_user['role'] == 'admin' and hasattr(self, 'nav_buttons'):
            from database import get_pending_approval_requests
            pending = get_pending_approval_requests()
            count = len(pending)
            badge = f' ({count})' if count > 0 else ''
            if 'loan_approvals' in self.nav_buttons:
                self.nav_buttons['loan_approvals'].config(text=f'🔐 Approvals{badge}')

        # Scroll to top immediately, and again after render/layout settles.
        self.page_canvas.yview_moveto(0)

        header_map = {
            'dashboard': 'Dashboard',
            'new_ticket': 'New Loan Ticket',
            'loan_list': 'Loan Management',
            'loan_detail': 'Loan Details',
            'loan_history': 'Loan History',
            'renew_loan': 'Renew Loan',
            'redeem_loan': 'Redeem Loan',
            'customers': 'Customer Management',
            'letters': 'Letters Center',
            'admin_settings': 'Admin Settings',
            'reports': 'Reports',
            'loan_approvals': 'Loan Approval Requests',
            'print_ticket': 'Print Ticket',
        }
        self.header_label.config(text=header_map.get(page_name, page_name.title()))

        if page_name == 'dashboard':
            from pages.dashboard import DashboardPage
            DashboardPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'new_ticket':
            from pages.new_ticket import NewTicketPage
            NewTicketPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'loan_list':
            from pages.loan_pages import LoanListPage
            LoanListPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'loan_detail':
            from pages.loan_pages import LoanDetailPage
            LoanDetailPage(self.page_content, self.theme, self.current_user, self.navigate, param).render()

        elif page_name == 'loan_history':
            from pages.loan_pages import LoanHistoryPage
            LoanHistoryPage(self.page_content, self.theme, self.current_user, self.navigate, param).render()

        elif page_name == 'renew_loan':
            from pages.loan_actions import RenewLoanPage
            RenewLoanPage(self.page_content, self.theme, self.current_user, self.navigate, param).render()

        elif page_name == 'redeem_loan':
            from pages.loan_actions import RedeemLoanPage
            RedeemLoanPage(self.page_content, self.theme, self.current_user, self.navigate, param).render()

        elif page_name == 'customers':
            from pages.customers import CustomersPage
            CustomersPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'letters':
            from pages.letters import LettersPage
            kwargs = {}
            if param and isinstance(param, dict):
                kwargs = param
            LettersPage(self.page_content, self.theme, self.current_user, self.navigate, **kwargs).render()

        elif page_name == 'admin_settings':
            from pages.admin_settings import AdminSettingsPage
            AdminSettingsPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'reports':
            from pages.reports import ReportsPage
            ReportsPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'loan_approvals':
            from pages.loan_approvals import LoanApprovalsPage
            LoanApprovalsPage(self.page_content, self.theme, self.current_user, self.navigate).render()

        elif page_name == 'print_ticket':
            from pages.print_ticket import PrintTicketPage
            PrintTicketPage(self.page_content, self.theme, self.current_user, self.navigate, param).render()

        # Some pages resize async; enforce top position after geometry updates to avoid blank top gaps.
        self.root.after_idle(lambda: self.page_canvas.yview_moveto(0))

    def _logout(self):
        if messagebox.askyesno("Logout", "Are you sure you want to logout?"):
            self.current_user = None
            self._show_login()

    def _on_closing(self):
        """Handle app closing quickly without blocking UI on network calls."""
        try:
            if self.backup_manager:
                self.backup_manager.create_backup_and_queue()
            threading.Thread(target=self._send_shutdown, daemon=True).start()
        except Exception as e:
            print(f"Warning: Failed to start shutdown notifier: {e}")
        finally:
            self.root.destroy()

    def create_backup_after_action(self):
        """Create a backup after important actions"""
        try:
            if self.backup_manager:
                self.backup_manager.create_backup_and_queue()
                self.backup_manager.sync_pending_uploads()
        except Exception as e:
            print(f"Warning: Failed to create backup: {e}")

    def run(self):
        self.root.mainloop()


if __name__ == '__main__':
    app = GoldLoanSystemApp()
    app.run()
