/**
 * Python Application Template Generator
 * Generates complete Python desktop applications dynamically
 */

/**
 * Generate complete Python application code
 */
function generatePythonApp({ systemName, category, tables, features, tier }) {
  const className = systemName.replace(/\s+/g, '');
  const dbName = `${category}_${tier}`;
  
  return `"""
${systemName} - ${tier.toUpperCase()} Edition
Auto-generated by ZORO9X SaaS Platform
"""

import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import sqlite3
import json
import requests
import os
from datetime import datetime, timedelta
from pathlib import Path
import threading
import time

# Configuration
CONFIG_FILE = '${category}_config.json'
BUSINESS_CONFIG_FILE = 'business_config.json'
API_BASE_URL = 'http://localhost:5001/api/saas'

# Load business configuration
def load_business_config():
    """Load business-specific configuration"""
    if os.path.exists(BUSINESS_CONFIG_FILE):
        with open(BUSINESS_CONFIG_FILE, 'r') as f:
            return json.load(f)
    return {}

BUSINESS_CONFIG = load_business_config()


class ${className}App:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("${systemName} - ${tier.charAt(0).toUpperCase() + tier.slice(1)} Edition")
        self.root.geometry("1400x800")
        self.root.configure(bg='#f5f7fa')
        
        # Load configuration
        self.config = self.load_config()
        self.api_key = self.config.get('api_key', '')
        
        # Database configuration
        db_name = self.config.get('database_name', '${dbName}_database')
        self.db_file = self.config.get('database_path', f'{db_name}.db')
        
        # Load business configuration
        self.business_config = BUSINESS_CONFIG
        business_details = self.business_config.get('business_details', {})
        self.company_name = business_details.get('name', self.config.get('company_name', 'My Business'))
        self.business_phone = business_details.get('phone', '')
        self.business_email = business_details.get('email', '')
        self.business_address = business_details.get('address', '')
        
        # License validation state
        self.license_valid = False
        self.last_validation = None
        
        # Initialize database
        self.init_database()
        
        # Start license validation thread
        threading.Thread(target=self.background_license_check, daemon=True).start()
        
        # Show setup or main UI
        if not self.api_key:
            self.show_setup_wizard()
        else:
            validation_result = self.validate_license()
            if validation_result or self.business_config:
                self.create_main_ui()
            else:
                messagebox.showerror("License Error", "Failed to validate license.")
                self.root.quit()
    
    def load_config(self):
        """Load configuration from file"""
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                return json.load(f)
        return {}
    
    def save_config(self):
        """Save configuration to file"""
        with open(CONFIG_FILE, 'w') as f:
            json.dump(self.config, f, indent=2)
    
    def validate_license(self):
        """Validate API key with server"""
        try:
            # Check offline mode first
            if self.business_config:
                end_date_str = self.business_config.get('end_date')
                if end_date_str:
                    try:
                        end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
                        if datetime.now() < end_date:
                            self.license_valid = True
                            self.last_validation = datetime.now()
                            return True
                    except:
                        pass
            
            # Try online validation
            response = requests.post(
                f'{API_BASE_URL}/validate-key',
                json={'api_key': self.api_key},
                timeout=5
            )
            
            if response.status_code == 200:
                data = response.json()
                self.license_valid = data.get('valid', False)
                self.last_validation = datetime.now()
                return self.license_valid
            return False
        except Exception as e:
            print(f"License validation error: {e}")
            if self.business_config:
                return True
            if self.last_validation:
                grace_period = datetime.now() - self.last_validation
                return grace_period.days < 3
            return False
    
    def background_license_check(self):
        """Background thread to periodically check license"""
        while True:
            time.sleep(86400)  # Check every 24 hours
            if not self.validate_license():
                self.root.after(0, self.show_license_error)
    
    def show_license_error(self):
        """Show license error and close app"""
        messagebox.showerror(
            "License Expired",
            "Your subscription has expired. Please renew your subscription."
        )
        self.root.quit()
    
    def show_setup_wizard(self):
        """Show initial setup wizard"""
        setup_window = tk.Toplevel(self.root)
        setup_window.title("Setup Wizard")
        setup_window.geometry("600x400")
        setup_window.configure(bg='#f5f7fa')
        setup_window.transient(self.root)
        setup_window.grab_set()
        
        tk.Label(
            setup_window,
            text="Welcome to ${systemName}",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(pady=30)
        
        tk.Label(
            setup_window,
            text="Please enter your API key to continue",
            font=('Segoe UI', 11),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=10)
        
        api_entry = tk.Entry(setup_window, font=('Segoe UI', 11), width=40)
        api_entry.pack(pady=20)
        
        def save_and_continue():
            api_key = api_entry.get().strip()
            if not api_key:
                messagebox.showerror("Error", "Please enter an API key")
                return
            
            self.api_key = api_key
            self.config['api_key'] = api_key
            self.save_config()
            
            if self.validate_license():
                setup_window.destroy()
                self.create_main_ui()
            else:
                messagebox.showerror("Error", "Invalid API key")
        
        tk.Button(
            setup_window,
            text="Continue",
            font=('Segoe UI', 11, 'bold'),
            bg='#2563eb',
            fg='white',
            padx=30,
            pady=10,
            cursor='hand2',
            command=save_and_continue
        ).pack(pady=20)
    
    def init_database(self):
        """Initialize SQLite database with tables"""
        conn = sqlite3.connect(self.db_file)
        cursor = conn.cursor()
        
${generateTableSQL(tables, tier)}
        
        conn.commit()
        conn.close()
    
    def create_main_ui(self):
        """Create main application interface"""
        # Sidebar
        sidebar = tk.Frame(self.root, bg='#2563eb', width=250)
        sidebar.pack(side=tk.LEFT, fill=tk.Y)
        sidebar.pack_propagate(False)
        
        # Logo/Header
        logo_frame = tk.Frame(sidebar, bg='#1d4ed8', height=80)
        logo_frame.pack(fill=tk.X)
        logo_frame.pack_propagate(False)
        
        tk.Label(
            logo_frame,
            text=self.company_name,
            font=('Segoe UI', 16, 'bold'),
            bg='#1d4ed8',
            fg='white',
            wraplength=230
        ).pack(pady=20)
        
        # Navigation
        nav_frame = tk.Frame(sidebar, bg='#2563eb')
        nav_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=20)
        
${generateNavigationButtons(features)}
        
        # Logout button
        tk.Button(
            sidebar,
            text="🚪 Logout",
            font=('Segoe UI', 11),
            bg='#dc2626',
            fg='white',
            relief='flat',
            padx=20,
            pady=10,
            cursor='hand2',
            command=self.logout
        ).pack(side=tk.BOTTOM, pady=20, padx=10, fill=tk.X)
        
        # Content area
        self.content_frame = tk.Frame(self.root, bg='#f5f7fa')
        self.content_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)
        
        # Header
        header = tk.Frame(self.content_frame, bg='white', height=60)
        header.pack(fill=tk.X)
        header.pack_propagate(False)
        
        tk.Label(
            header,
            text="${systemName}",
            font=('Segoe UI', 18, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack(side=tk.LEFT, padx=30, pady=15)
        
        tk.Label(
            header,
            text=datetime.now().strftime("%B %d, %Y"),
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack(side=tk.RIGHT, padx=30)
        
        # Show dashboard
        self.show_dashboard()
    
    def show_dashboard(self):
        """Display dashboard view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        dashboard_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        dashboard_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            dashboard_frame,
            text="📊 Dashboard",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Stats cards
        stats_frame = tk.Frame(dashboard_frame, bg='#f5f7fa')
        stats_frame.pack(fill=tk.X, pady=10)
        
        self.create_stat_card(stats_frame, "📝 Total Records", "0", "#3b82f6")
        self.create_stat_card(stats_frame, "✅ Active", "0", "#10b981")
        self.create_stat_card(stats_frame, "⏰ Pending", "0", "#f59e0b")
        
        # Welcome message
        tk.Label(
            dashboard_frame,
            text=f"Welcome to {self.company_name}!",
            font=('Segoe UI', 14),
            bg='#f5f7fa',
            fg='#475569'
        ).pack(pady=30)
    
    def create_stat_card(self, parent, title, value, color):
        """Create a statistics card"""
        card = tk.Frame(parent, bg='white', relief=tk.SOLID, bd=1)
        card.pack(side=tk.LEFT, padx=10, ipadx=30, ipady=20)
        card.config(highlightbackground='#e2e8f0', highlightthickness=1)
        
        icon_frame = tk.Frame(card, bg=color, width=50, height=50)
        icon_frame.pack(pady=(0, 10))
        icon_frame.pack_propagate(False)
        
        tk.Label(
            card,
            text=title,
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack()
        
        tk.Label(
            card,
            text=value,
            font=('Segoe UI', 24, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack()
    
${generateFeatureMethods(features, tables, tier)}
    
    def logout(self):
        """Logout and close application"""
        if messagebox.askyesno("Logout", "Are you sure you want to logout?"):
            self.root.quit()
    
    def run(self):
        """Run the application"""
        self.root.mainloop()


if __name__ == '__main__':
    app = ${className}App()
    app.run()
`;
}

/**
 * Generate SQL table creation statements
 */
function generateTableSQL(tables, tier) {
  if (!tables || tables.length === 0) {
    return '        # No tables defined';
  }
  
  return tables.map(table => {
    if (!table.fields || table.fields.length === 0) {
      return `        # Skipping ${table.name} - no fields defined`;
    }
    
    const fields = table.fields.map(field => {
      let sql = `            ${field.name} ${field.type}`;
      if (field.primaryKey) sql += ' PRIMARY KEY AUTOINCREMENT';
      if (field.unique) sql += ' UNIQUE';
      if (field.notNull) sql += ' NOT NULL';
      if (field.default !== undefined) sql += ` DEFAULT ${field.default}`;
      return sql;
    }).join(',\n');
    
    return `        # Create ${table.name} table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS ${table.name} (
${fields}
            )
        ''')`;
  }).join('\n\n');
}

/**
 * Generate navigation buttons
 */
function generateNavigationButtons(features) {
  return features.map((feature, index) => {
    const methodName = `show_${feature.toLowerCase().replace(/\s+/g, '_')}`;
    const icon = getFeatureIcon(feature);
    
    return `        nav_btn_${index} = tk.Button(
            nav_frame,
            text="${icon} ${feature}",
            font=('Segoe UI', 11),
            bg='#2563eb',
            fg='white',
            activebackground='#1d4ed8',
            activeforeground='white',
            relief='flat',
            anchor='w',
            padx=20,
            pady=12,
            cursor='hand2',
            command=self.${methodName}
        )
        nav_btn_${index}.pack(fill=tk.X, pady=5)`;
  }).join('\n\n');
}

/**
 * Generate feature methods
 */
function generateFeatureMethods(features, tables, tier) {
  return features.map(feature => {
    const methodName = `show_${feature.toLowerCase().replace(/\s+/g, '_')}`;
    const relatedTable = findRelatedTable(feature, tables);
    
    return `    def ${methodName}(self):
        """Display ${feature} view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        view_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        view_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            view_frame,
            text="${getFeatureIcon(feature)} ${feature}",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Add your ${feature} functionality here
        tk.Label(
            view_frame,
            text="${feature} feature coming soon!",
            font=('Segoe UI', 12),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=50)
${tier === 'premium' ? generatePremiumFeature(feature) : ''}`;
  }).join('\n\n');
}

/**
 * Generate premium-specific features
 */
function generatePremiumFeature(feature) {
  return `
        
        # Premium Feature: Advanced Analytics
        premium_frame = tk.Frame(view_frame, bg='#fef3c7', relief=tk.SOLID, bd=1)
        premium_frame.pack(fill=tk.X, pady=10, padx=20, ipady=10)
        
        tk.Label(
            premium_frame,
            text="⭐ Premium Feature",
            font=('Segoe UI', 10, 'bold'),
            bg='#fef3c7',
            fg='#92400e'
        ).pack(pady=5)`;
}

/**
 * Get icon for feature
 */
function getFeatureIcon(feature) {
  const iconMap = {
    'dashboard': '📊',
    'records': '📝',
    'management': '👥',
    'reports': '📈',
    'settings': '⚙️',
    'analytics': '📉',
    'inventory': '📦',
    'orders': '🛒',
    'sales': '💰',
    'customers': '👤',
    'products': '🏷️'
  };
  
  const key = Object.keys(iconMap).find(k => 
    feature.toLowerCase().includes(k)
  );
  
  return iconMap[key] || '📋';
}

/**
 * Find related table for a feature
 */
function findRelatedTable(feature, tables) {
  const featureLower = feature.toLowerCase().replace(/\s+/g, '_');
  return tables.find(t => 
    t.name.includes(featureLower) || 
    featureLower.includes(t.name)
  );
}

module.exports = { generatePythonApp };
