/**
 * Python Application Template Generator
 * Generates complete Python desktop applications dynamically
 */

/**
 * Generate complete Python application code
 */
function generatePythonApp({ systemName, category, tables, features, tier }) {
  const className = systemName.replace(/\s+/g, '');
  const dbName = `${category}_${tier}`;
    const tokenVerifySecret = (process.env.OFFLINE_TOKEN_SECRET || process.env.JWT_SECRET || 'your-secret-key')
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'");
    const configSigningSecret = (process.env.CONFIG_SIGNING_SECRET || process.env.OFFLINE_TOKEN_SECRET || process.env.JWT_SECRET || 'config-signing-secret')
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'");
    const publicApiUrl = (process.env.ZORO9X_PUBLIC_API_URL || process.env.ZORO9X_API_URL || '')
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'");
  
  return `"""
${systemName} - ${tier.toUpperCase()} Edition
Auto-generated by ZORO9X SaaS Platform
"""

import tkinter as tk
from tkinter import ttk, messagebox, filedialog
import sqlite3
import json
import os
import hashlib
import platform
import uuid
import requests
from datetime import datetime
import base64
import sys
import hmac

# Configuration
APP_DIR = os.path.dirname(sys.executable) if getattr(sys, 'frozen', False) else os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(APP_DIR, '${category}_config.json')
LICENSE_CACHE_FILE = os.path.join(APP_DIR, '${category}_license.json')
DEFAULT_LOCAL_LOGO_PATH = os.path.join(APP_DIR, 'logo.png')
DEFAULT_OFFLINE_GRACE_DAYS = 7
API_URL = '${publicApiUrl}'
VALIDATE_ENDPOINT = '/api/saas/validate-key'
ACTIVATE_ENDPOINT = '/api/saas/activate-device'
TOKEN_VERIFY_SECRET = '${tokenVerifySecret}'
CONFIG_SIGNING_SECRET = '${configSigningSecret}'
VALIDATION_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_VALIDATE_TIMEOUT_SECONDS', '4'))
ACTIVATION_TIMEOUT_SECONDS = float(os.getenv('ZORO9X_ACTIVATE_TIMEOUT_SECONDS', '4'))


def get_effective_api_url():
    return API_URL.rstrip('/')


def is_remote_api_url(url):
    normalized = (url or '').strip().lower()
    return bool(normalized and (normalized.startswith('http://') or normalized.startswith('https://')))


def xor_bytes(data, key_material):
    key = hashlib.sha256(key_material.encode()).digest()
    return bytes(byte ^ key[index % len(key)] for index, byte in enumerate(data))


def encrypt_config_value(value, device_fp):
    if not value:
        return ''
    encrypted = xor_bytes(value.encode('utf-8'), f'config:{device_fp}')
    return base64.b64encode(encrypted).decode('utf-8')


def decrypt_config_value(value, device_fp):
    if not value:
        return ''
    try:
        decoded = base64.b64decode(value.encode('utf-8'))
        decrypted = xor_bytes(decoded, f'config:{device_fp}')
        return decrypted.decode('utf-8')
    except Exception:
        return value


def get_config_value(config, encrypted_key, device_fp, default=''):
    encrypted_value = config.get(encrypted_key, '')
    if encrypted_value:
        return decrypt_config_value(encrypted_value, device_fp)
    return default


def sign_config(config_data, device_fp):
    """Sign encrypted config fields to detect local tampering."""
    signable = {
        'api_key_encrypted': config_data.get('api_key_encrypted', ''),
        'company_name_encrypted': config_data.get('company_name_encrypted', ''),
        'contact_email_encrypted': config_data.get('contact_email_encrypted', ''),
        'contact_phone_encrypted': config_data.get('contact_phone_encrypted', ''),
        'business_address_encrypted': config_data.get('business_address_encrypted', ''),
        'logo_url_encrypted': config_data.get('logo_url_encrypted', ''),
        'database_name': config_data.get('database_name', ''),
        'database_path': config_data.get('database_path', ''),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        CONFIG_SIGNING_SECRET.encode('utf-8'),
        f'config:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_config_signature(config_data, device_fp):
    expected = sign_config(config_data, device_fp)
    provided = config_data.get('config_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def get_device_fingerprint():
    """Generate a stable device fingerprint from hardware identifiers."""
    raw = '|'.join([platform.node(), platform.machine(), str(uuid.getnode())])
    return hashlib.sha256(raw.encode()).hexdigest()[:32]


def get_mac_address():
    """Return local MAC address in colon format for device tracking."""
    mac_num = uuid.getnode()
    mac_hex = f'{mac_num:012x}'
    return ':'.join(mac_hex[i:i+2] for i in range(0, 12, 2))


def parse_token_payload(token):
    """Decode token payload from server token format."""
    try:
        if not token or '.' not in token:
            return {}
        payload_part = token.split('.', 1)[0]
        payload_part += '=' * (-len(payload_part) % 4)
        raw = base64.b64decode(payload_part.encode())
        return json.loads(raw.decode())
    except Exception:
        return {}


def verify_server_signed_token(token):
    """Verify server signature for offline token usage."""
    try:
        if not token or '.' not in token:
            return False, {}

        payload_part, signature = token.split('.', 1)
        if not payload_part or not signature:
            return False, {}

        expected = hmac.new(
            TOKEN_VERIFY_SECRET.encode('utf-8'),
            payload_part.encode('utf-8'),
            hashlib.sha256,
        ).hexdigest()

        if not hmac.compare_digest(signature, expected):
            return False, {}

        payload = parse_token_payload(token)
        return bool(payload), payload
    except Exception:
        return False, {}


def sign_cache(cache_data, device_fp):
    """Sign local cache to detect manual edits."""
    signable = {
        'valid': cache_data.get('valid', False),
        'last_check': cache_data.get('last_check', ''),
        'token': cache_data.get('token', ''),
        'subscription_id': cache_data.get('subscription_id'),
        'device_fingerprint': cache_data.get('device_fingerprint', ''),
        'grace_period_days': cache_data.get('grace_period_days', DEFAULT_OFFLINE_GRACE_DAYS),
    }
    material = json.dumps(signable, sort_keys=True, separators=(',', ':'))
    return hmac.new(
        TOKEN_VERIFY_SECRET.encode('utf-8'),
        f'cache:{device_fp}:{material}'.encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()


def verify_cache_signature(cache_data, device_fp):
    expected = sign_cache(cache_data, device_fp)
    provided = cache_data.get('cache_signature', '')
    return bool(provided) and hmac.compare_digest(provided, expected)


def load_license_cache():
    if os.path.exists(LICENSE_CACHE_FILE):
        try:
            with open(LICENSE_CACHE_FILE, 'r') as f:
                return json.load(f)
        except Exception:
            return {}
    return {}


def save_license_cache(data):
    try:
        with open(LICENSE_CACHE_FILE, 'w') as f:
            json.dump(data, f, indent=2)
    except Exception:
        pass


class ${className}App:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title("${systemName} - ${tier.charAt(0).toUpperCase() + tier.slice(1)} Edition")
        self.root.geometry("1400x800")
        self.root.configure(bg='#f5f7fa')
        self.set_window_icon()
        
        # Load configuration
        self.config = self.load_config()
        
        # Database configuration
        db_name = self.config.get('database_name', '${dbName}_database')
        db_path = self.config.get('database_path', f'{db_name}.db')
        self.db_file = db_path if os.path.isabs(db_path) else os.path.join(APP_DIR, db_path)

        self.company_name = self.config.get('company_name', 'My Business')
        self.business_phone = self.config.get('contact_phone', '')
        self.business_email = self.config.get('contact_email', '')
        self.business_address = self.config.get('business_address', '')
        self.logo_url = self.config.get('logo_url', '')

        # Validate license before allowing access
        if not self.validate_license():
            self.root.destroy()
            return
        
        # Initialize database
        self.init_database()

        self.create_main_ui()

    def set_window_icon(self):
        bundle_dir = getattr(sys, '_MEIPASS', '') if getattr(sys, 'frozen', False) else ''
        icon_candidates = [
            os.path.join(APP_DIR, 'logo.ico'),
            os.path.join(APP_DIR, 'app.ico'),
        ]
        if bundle_dir:
            icon_candidates.extend([
                os.path.join(bundle_dir, 'logo.ico'),
                os.path.join(bundle_dir, 'app.ico'),
            ])
        for icon_path in icon_candidates:
            if os.path.exists(icon_path):
                try:
                    self.root.iconbitmap(icon_path)
                    return
                except Exception:
                    pass

        logo_candidates = [DEFAULT_LOCAL_LOGO_PATH]
        if bundle_dir:
            logo_candidates.append(os.path.join(bundle_dir, 'logo.png'))

        for logo_path in logo_candidates:
            if not os.path.exists(logo_path):
                continue
            try:
                self._window_icon_image = tk.PhotoImage(file=logo_path)
                self.root.iconphoto(True, self._window_icon_image)
                return
            except Exception:
                pass
    
    def load_config(self):
        """Load configuration from file and decrypt protected values."""
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r') as f:
                config = json.load(f)

            device_fp = get_device_fingerprint()
            if not verify_config_signature(config, device_fp):
                messagebox.showerror(
                    'Configuration Tampered',
                    'Local configuration signature is invalid.\\nPlease reinstall or re-run activation.'
                )
                return {}

            config['api_key'] = get_config_value(config, 'api_key_encrypted', device_fp)
            config['company_name'] = get_config_value(config, 'company_name_encrypted', device_fp, 'My Business')
            config['contact_email'] = get_config_value(config, 'contact_email_encrypted', device_fp)
            config['contact_phone'] = get_config_value(config, 'contact_phone_encrypted', device_fp)
            config['business_address'] = get_config_value(config, 'business_address_encrypted', device_fp)
            config['logo_url'] = get_config_value(config, 'logo_url_encrypted', device_fp)
            return config
        return {}
    
    def save_config(self):
        """Save configuration to file with machine-tied api key encryption."""
        persistable = dict(self.config)
        device_fp = get_device_fingerprint()

        for plain_key, encrypted_key in [
            ('api_key', 'api_key_encrypted'),
            ('company_name', 'company_name_encrypted'),
            ('contact_email', 'contact_email_encrypted'),
            ('contact_phone', 'contact_phone_encrypted'),
            ('business_address', 'business_address_encrypted'),
            ('logo_url', 'logo_url_encrypted'),
        ]:
            plain_value = persistable.pop(plain_key, '')
            if plain_value:
                persistable[encrypted_key] = encrypt_config_value(str(plain_value), device_fp)

        persistable['config_signature'] = sign_config(persistable, device_fp)

        with open(CONFIG_FILE, 'w') as f:
            json.dump(persistable, f, indent=2)

    # ------------------------------------------------------------------
    # License validation
    # ------------------------------------------------------------------

    def validate_license(self):
        """Online-first validation with short offline fallback using signed token."""
        api_key = self.config.get('api_key', '')
        if not api_key:
            messagebox.showerror(
                'Configuration Required',
                'No API key found.\\nPlease reinstall the application with a valid API key.'
            )
            return False

        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            messagebox.showerror(
                'Remote Verification Required',
                'Remote HTTPS license API is not configured.\\nPlease set ZORO9X_PUBLIC_API_URL.'
            )
            return False

        device_fp = get_device_fingerprint()
        device_info = {
            'device_name': platform.node(),
            'os': f'{platform.system()} {platform.release()}',
            'machine': platform.machine(),
            'mac_address': get_mac_address(),
        }
        try:
            resp = requests.post(
                f'{api_url}{VALIDATE_ENDPOINT}',
                json={'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                timeout=VALIDATION_TIMEOUT_SECONDS,
            )
            data = resp.json()
            if resp.status_code == 200 and data.get('valid'):
                grace_period_days = int(data.get('grace_period_days') or DEFAULT_OFFLINE_GRACE_DAYS)
                cache_data = {
                    'valid': True,
                    'last_check': datetime.now().isoformat(),
                    'token': data.get('token', ''),
                    'subscription_id': data.get('subscription', {}).get('id'),
                    'device_fingerprint': device_fp,
                    'grace_period_days': grace_period_days,
                }
                cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                save_license_cache(cache_data)
                return True
            if resp.status_code == 403 and 'not activated' in data.get('message', '').lower():
                return self._activate_device(api_key, device_fp, device_info)
            messagebox.showerror(
                'License Error',
                data.get('message', 'License validation failed. Please contact support.')
            )
            return False
        except requests.exceptions.ConnectionError:
            return self._check_offline_grace()
        except Exception:
            return self._check_offline_grace()

    def _activate_device(self, api_key, device_fp, device_info):
        """Register this device with the license server for the first time."""
        api_url = get_effective_api_url()
        if not is_remote_api_url(api_url):
            return False

        try:
            resp = requests.post(
                f'{api_url}{ACTIVATE_ENDPOINT}',
                json={'api_key': api_key, 'device_fingerprint': device_fp, 'device_info': device_info},
                timeout=ACTIVATION_TIMEOUT_SECONDS,
            )
            data = resp.json()
            if resp.status_code == 200 and data.get('success'):
                cache_data = {
                    'valid': True,
                    'last_check': datetime.now().isoformat(),
                    'token': data.get('token', ''),
                    'subscription_id': data.get('subscription', {}).get('id'),
                    'device_fingerprint': device_fp,
                    'grace_period_days': int(data.get('grace_period_days') or DEFAULT_OFFLINE_GRACE_DAYS),
                }
                cache_data['cache_signature'] = sign_cache(cache_data, device_fp)
                save_license_cache(cache_data)
                return True
            if resp.status_code == 202:
                messagebox.showinfo(
                    'Activation Pending',
                    'This device is awaiting administrator approval.\\n'
                    'You will be able to use the application once approved.\\n'
                    'Contact support if this takes more than 24 hours.'
                )
                return False
            messagebox.showerror(
                'Activation Failed',
                data.get('message', 'Device activation failed. Please contact support.')
            )
            return False
        except Exception:
            return self._check_offline_grace()

    def _check_offline_grace(self):
        """Allow temporary offline usage if cached server token is valid."""
        cache = load_license_cache()
        device_fp = get_device_fingerprint()

        if not cache.get('valid'):
            messagebox.showerror(
                'Internet Required',
                'No valid offline token found.\\nPlease connect to internet and start again.'
            )
            return False

        if cache.get('device_fingerprint') and cache.get('device_fingerprint') != device_fp:
            messagebox.showerror(
                'License Mismatch',
                'Offline token belongs to another device.\\nPlease reconnect to validate this machine.'
            )
            return False

        if not verify_cache_signature(cache, device_fp):
            messagebox.showerror(
                'License Cache Tampered',
                'Local license cache was modified.\\nPlease reconnect to obtain a fresh token.'
            )
            return False

        token = cache.get('token', '')
        is_token_valid, token_payload = verify_server_signed_token(token)
        if not is_token_valid:
            messagebox.showerror(
                'Invalid Offline Token',
                'Server token signature validation failed.\\nPlease reconnect to refresh your license.'
            )
            return False

        expires_ms = int(token_payload.get('expires', 0) or 0)
        token_device = token_payload.get('device')
        token_sub = token_payload.get('sub_id')
        cache_sub = cache.get('subscription_id')

        if token_device and token_device != device_fp:
            messagebox.showerror(
                'Device Binding Failed',
                'Offline token is not valid for this device.\\nPlease reconnect to renew license.'
            )
            return False

        if token_sub and cache_sub and str(token_sub) != str(cache_sub):
            messagebox.showerror(
                'Subscription Binding Failed',
                'Offline token does not match this subscription.\\nPlease reconnect to renew license.'
            )
            return False

        if expires_ms and datetime.now().timestamp() * 1000 > expires_ms:
            messagebox.showerror(
                'Offline Token Expired',
                'Stored token has expired.\\nPlease connect to internet to refresh your license.'
            )
            return False

        grace_period_days = int(cache.get('grace_period_days') or DEFAULT_OFFLINE_GRACE_DAYS)
        try:
            last_check = datetime.fromisoformat(cache.get('last_check', '2000-01-01T00:00:00'))
        except Exception:
            messagebox.showerror(
                'License Cache Invalid',
                'Offline cache timestamp is invalid.\\nPlease reconnect to refresh your license.'
            )
            return False

        days_offline = (datetime.now() - last_check).days
        if days_offline > grace_period_days:
            messagebox.showerror(
                'Offline Grace Period Expired',
                f'No server contact for {days_offline} days (limit: {grace_period_days}).\\n'
                'Please connect to internet to continue.'
            )
            return False

        remaining = grace_period_days - days_offline
        if remaining <= 2:
            messagebox.showwarning(
                'Offline Mode',
                f'Running in offline mode. Internet required within {remaining} day(s).'
            )

        return True

    # ------------------------------------------------------------------

    def init_database(self):
        """Initialize SQLite database with tables"""
        conn = sqlite3.connect(self.db_file)
        cursor = conn.cursor()
        
${generateTableSQL(tables, tier)}
        
        conn.commit()
        conn.close()
    
    def create_main_ui(self):
        """Create main application interface"""
        # Sidebar
        sidebar = tk.Frame(self.root, bg='#2563eb', width=250)
        sidebar.pack(side=tk.LEFT, fill=tk.Y)
        sidebar.pack_propagate(False)
        
        # Logo/Header
        logo_frame = tk.Frame(sidebar, bg='#1d4ed8', height=80)
        logo_frame.pack(fill=tk.X)
        logo_frame.pack_propagate(False)
        
        tk.Label(
            logo_frame,
            text=self.company_name,
            font=('Segoe UI', 16, 'bold'),
            bg='#1d4ed8',
            fg='white',
            wraplength=230
        ).pack(pady=20)
        
        # Navigation
        nav_frame = tk.Frame(sidebar, bg='#2563eb')
        nav_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=20)
        
${generateNavigationButtons(features)}
        
        # Logout button
        tk.Button(
            sidebar,
            text="🚪 Logout",
            font=('Segoe UI', 11),
            bg='#dc2626',
            fg='white',
            relief='flat',
            padx=20,
            pady=10,
            cursor='hand2',
            command=self.logout
        ).pack(side=tk.BOTTOM, pady=20, padx=10, fill=tk.X)
        
        # Content area
        self.content_frame = tk.Frame(self.root, bg='#f5f7fa')
        self.content_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)
        
        # Header
        header = tk.Frame(self.content_frame, bg='white', height=60)
        header.pack(fill=tk.X)
        header.pack_propagate(False)
        
        tk.Label(
            header,
            text="${systemName}",
            font=('Segoe UI', 18, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack(side=tk.LEFT, padx=30, pady=15)
        
        tk.Label(
            header,
            text=datetime.now().strftime("%B %d, %Y"),
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack(side=tk.RIGHT, padx=30)
        
        # Show dashboard
        self.show_dashboard()
    
    def show_dashboard(self):
        """Display dashboard view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        dashboard_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        dashboard_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            dashboard_frame,
            text="📊 Dashboard",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Stats cards
        stats_frame = tk.Frame(dashboard_frame, bg='#f5f7fa')
        stats_frame.pack(fill=tk.X, pady=10)
        
        self.create_stat_card(stats_frame, "📝 Total Records", "0", "#3b82f6")
        self.create_stat_card(stats_frame, "✅ Active", "0", "#10b981")
        self.create_stat_card(stats_frame, "⏰ Pending", "0", "#f59e0b")
        
        # Welcome message
        tk.Label(
            dashboard_frame,
            text=f"Welcome to {self.company_name}!",
            font=('Segoe UI', 14),
            bg='#f5f7fa',
            fg='#475569'
        ).pack(pady=30)
    
    def create_stat_card(self, parent, title, value, color):
        """Create a statistics card"""
        card = tk.Frame(parent, bg='white', relief=tk.SOLID, bd=1)
        card.pack(side=tk.LEFT, padx=10, ipadx=30, ipady=20)
        card.config(highlightbackground='#e2e8f0', highlightthickness=1)
        
        icon_frame = tk.Frame(card, bg=color, width=50, height=50)
        icon_frame.pack(pady=(0, 10))
        icon_frame.pack_propagate(False)
        
        tk.Label(
            card,
            text=title,
            font=('Segoe UI', 10),
            bg='white',
            fg='#64748b'
        ).pack()
        
        tk.Label(
            card,
            text=value,
            font=('Segoe UI', 24, 'bold'),
            bg='white',
            fg='#1e293b'
        ).pack()
    
${generateFeatureMethods(features, tables, tier)}
    
    def logout(self):
        """Logout and close application"""
        if messagebox.askyesno("Logout", "Are you sure you want to logout?"):
            self.root.quit()
    
    def run(self):
        """Run the application"""
        self.root.mainloop()


if __name__ == '__main__':
    app = ${className}App()
    app.run()
`;
}

/**
 * Generate SQL table creation statements
 */
function generateTableSQL(tables, tier) {
  if (!tables || tables.length === 0) {
    return '        # No tables defined';
  }
  
  return tables.map(table => {
    if (!table.fields || table.fields.length === 0) {
      return `        # Skipping ${table.name} - no fields defined`;
    }
    
    const fields = table.fields.map(field => {
      let sql = `            ${field.name} ${field.type}`;
      if (field.primaryKey) sql += ' PRIMARY KEY AUTOINCREMENT';
      if (field.unique) sql += ' UNIQUE';
      if (field.notNull) sql += ' NOT NULL';
      if (field.default !== undefined) sql += ` DEFAULT ${field.default}`;
      return sql;
    }).join(',\n');
    
    return `        # Create ${table.name} table
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS ${table.name} (
${fields}
            )
        ''')`;
  }).join('\n\n');
}

/**
 * Generate navigation buttons
 */
function generateNavigationButtons(features) {
  return features.map((feature, index) => {
        const methodName = `show_${toPythonMethodSuffix(feature)}`;
    const icon = getFeatureIcon(feature);
    
    return `        nav_btn_${index} = tk.Button(
            nav_frame,
            text="${icon} ${feature}",
            font=('Segoe UI', 11),
            bg='#2563eb',
            fg='white',
            activebackground='#1d4ed8',
            activeforeground='white',
            relief='flat',
            anchor='w',
            padx=20,
            pady=12,
            cursor='hand2',
            command=self.${methodName}
        )
        nav_btn_${index}.pack(fill=tk.X, pady=5)`;
  }).join('\n\n');
}

/**
 * Generate feature methods
 */
function generateFeatureMethods(features, tables, tier) {
  return features.map(feature => {
        const methodName = `show_${toPythonMethodSuffix(feature)}`;
    const relatedTable = findRelatedTable(feature, tables);
    
    return `    def ${methodName}(self):
        """Display ${feature} view"""
        for widget in self.content_frame.winfo_children():
            if isinstance(widget, tk.Frame) and widget.winfo_y() > 0:
                widget.destroy()
        
        view_frame = tk.Frame(self.content_frame, bg='#f5f7fa')
        view_frame.pack(fill=tk.BOTH, expand=True, padx=30, pady=20)
        
        tk.Label(
            view_frame,
            text="${getFeatureIcon(feature)} ${feature}",
            font=('Segoe UI', 20, 'bold'),
            bg='#f5f7fa',
            fg='#1e293b'
        ).pack(anchor='w', pady=(0, 20))
        
        # Add your ${feature} functionality here
        tk.Label(
            view_frame,
            text="${feature} feature coming soon!",
            font=('Segoe UI', 12),
            bg='#f5f7fa',
            fg='#64748b'
        ).pack(pady=50)
${tier === 'premium' ? generatePremiumFeature(feature) : ''}`;
  }).join('\n\n');
}

/**
 * Generate premium-specific features
 */
function generatePremiumFeature(feature) {
  return `
        
        # Premium Feature: Advanced Analytics
        premium_frame = tk.Frame(view_frame, bg='#fef3c7', relief=tk.SOLID, bd=1)
        premium_frame.pack(fill=tk.X, pady=10, padx=20, ipady=10)
        
        tk.Label(
            premium_frame,
            text="⭐ Premium Feature",
            font=('Segoe UI', 10, 'bold'),
            bg='#fef3c7',
            fg='#92400e'
        ).pack(pady=5)`;
}

/**
 * Get icon for feature
 */
function getFeatureIcon(feature) {
  const iconMap = {
    'dashboard': '📊',
    'records': '📝',
    'management': '👥',
    'reports': '📈',
    'settings': '⚙️',
    'analytics': '📉',
    'inventory': '📦',
    'orders': '🛒',
    'sales': '💰',
    'customers': '👤',
    'products': '🏷️'
  };
  
  const key = Object.keys(iconMap).find(k => 
    feature.toLowerCase().includes(k)
  );
  
  return iconMap[key] || '📋';
}

/**
 * Find related table for a feature
 */
function findRelatedTable(feature, tables) {
    const featureLower = toPythonMethodSuffix(feature);
  return tables.find(t => 
    t.name.includes(featureLower) || 
    featureLower.includes(t.name)
  );
}

function toPythonMethodSuffix(feature) {
    const normalized = String(feature || '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');

    if (!normalized) {
        return 'feature';
    }

    if (/^[0-9]/.test(normalized)) {
        return `feature_${normalized}`;
    }

    return normalized;
}

module.exports = { generatePythonApp };
